### ISSUE TITLE
Make volume a function of frequency

### ISSUE THREAD

**Issue by ethanjurman** [RITAccess/data-analyzer#10]
higher pitches have a higher volume (it's a perceptual thing).
can we change that so if the majority of notes are higher (due to a low outlier) we can avoid hurting peoples ears?

where m1 is minimum note/freq, and m2 is maximum note/freq... this equation should suffice for volume.
http://www.wolframalpha.com/input/?i=m1%3D34%2C+m2%3D64%2C+cos%28%28x-m1%29%2F%28m2*pi%29%29

**Comment by ethanjurman** [comment]
We'll talk about this friday in more detail, before we implement or do anything, and then decide is it's a feature worth approaching.

**Comment by Rek3650** [comment]
I've done some more research into this subject and I think it is actually far more complicated than we initially thought. On this wiki page for [Equal-Loudness Contour](http://en.wikipedia.org/wiki/Equal-loudness_contour) you can find this graph ![Equal Loudness Contour Graph](http://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Lindos1.svg/400px-Lindos1.svg.png)
This graph is the tip of the iceberg for determining the proper sound pressure level (decibel) for a frequency for it to have the same perceived volume as another frequency. I also found many references to [ISO-226](http://www.iso.org/iso/catalogue_detail.htm?csnumber=34222) which appears to be a method that is an international standard for calculating these things. The problem is that the ISO seems to own the rights to these methods and they must be purchased to be used. I am going to attempt to implement the fix Ethan suggested but I doubt that it will properly adjust volume based on frequency.

**Comment by Rek3650** [comment]
There doesn't appear to be any easy solution to this. I decided to lower the volume slightly so that higher notes aren't quite as painful. I also increased the lower bounds of the frequency range so that there would be less high frequency notes.
