### ISSUE TITLE
"Data Plot" is read as "Data Points, group" when tab 

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#27]
It should be Data Plot instead of Data Points.

**Comment by smcintosh881** [comment]
From what I've read I think it adds group to the end because it is called a group, meaning it can be interacted with. Its like when it adds html to the end. I don't think there is a way to get rid of it. As for fixing Data Points, in line 40 of index.html if you change the title from "Data Points" to "Data Plot" it should work.
