### ISSUE TITLE
Bar Graph re-adjust

### ISSUE THREAD

**Issue by smcintosh881** [RITAccess/data-analyzer#46]
When you make certain bars invisible the original graph size stays in place. Is there a way to make the bar graphs change dynamically?

**Comment by erl7902** [comment]
Not without removing the data from the chart, I think. Since we're simply making the strokeColor of the bars invisible, it's not actually adjusting what's being sent to chart, so it wouldn't change the size that it thinks it needs to display all the data.

We could change it to add and remove data as bars are selected and deselected but that would get messy

**Comment by smcintosh881** [comment]
Ok. I know that the line one does this but probably not the same way as the bar would need it.

**Comment by jmiller656** [comment]
What browser are you doing this in? The graph resizes for me. I fixed this when we had the same problem with line graphs. What I ended up doing was temporarily storing the data somewhere else and then bringing it back once it was needed. Are you sure you were removing the dataset with the greatest points?

**Comment by baozi90** [comment]
For me, works in Safari and Firefox, and doesn't seem to work in Chrome.

**Comment by smcintosh881** [comment]
Chrome
