### ISSUE TITLE
Table Horizontal Scroll Disappears 

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#55]
When adding enough rows that the vertical scroll appears, the horizontal scroll disappears and the scrolling property is still there. This seems to only happen in Safari, and the horizontal scroll is still present in Chrome and Firefox. 

Safari:
![screen shot 2015-06-17 at 11 52 00](https://cloud.githubusercontent.com/assets/11864006/8212068/b6fb05d8-14e7-11e5-9ff4-19c2cbf2c855.png)

Chrome:
![screen shot 2015-06-17 at 11 53 10](https://cloud.githubusercontent.com/assets/11864006/8212069/b70133c2-14e7-11e5-871c-3ec0fd531fa7.png)

**Comment by smcintosh881** [comment]
I think this might have something to do with versions of browsers. In chrome i have the vertical scroll, safari has neither, firefox has both

**Comment by smcintosh881** [comment]
So I've looked into this and really cannot find a reason this happens. It most likely is because of the browser, thats why each one handles scrolling slightly differently. All three work functionally the same, however, they just look slightly different. I think we can disable the visual bar so none of them have it if we want a uniformed look.

**Comment by baozi90** [comment]
I'd say it's better to keep the scroll even if it's not unified.

**Comment by smcintosh881** [comment]
Ok, I think this issue could be closed then?
