### ISSUE TITLE
Issues with Toggling a Row off/on for Display

### ISSUE THREAD

**Issue by melissay94** [RITAccess/data-analyzer#59]
If you turn a row's data display off, switch your graph type, and then turn that same row's data display back on, it displays in the same form as the previous graph type. Ex. I have a line graph and turn a line off, switch to the bar graph, and turn that row back on, it still displays as points on a line.

**Comment by dmfRain4** [comment]
I was able to recreate this issue on master:head. I'd like to add a couple of key points.

I'd like to add that performing the steps to recreate this bug using the line and scatterplot graphs does not work. It seems they are represented in such a similar way that the "point-data" from the scatterplot do not appear as just dots on the line graph. In fact, even the line graph when "saved" is represented as points on the bar graph (just like the scatterplot). There is no tangible difference.

Second, the rows will maintain their shape/graph type/data type as long as they are not changed to another graph type while active. This means if a row is made innactive, the row will stay that way no matter how many other things are changed. Ex. Changed graph to bar graph, disabled the second line, proceeded to mess with the data, in every line, changed the graph type a couple of times, and then finally turned the second line back on. It retains it's bar graph shape and the old data before any changes were made. (Note that this is because data changes only occur when a change is made on an active graph))

Finally, beyond the other bug that I noticed, I noticed that another bug may exist with the data/graph shapes not shifting (when innactive) when the graph itself shifts along the x-axis because of a change to a label/row.

**Comment by dmfRain4** [comment]
As an edit to the above post, the line and scatter plot do have differences in terms of the shape of their "point shapes". For example, if a line has parallelograms for points on the lines. The points will retain their shape on the scatter plot (which is usually only circles). Conversely, if a particular line is usually represented with parallelogram point shapes, it will be represented by a circle instead if turned off on the scatter plot, and turned back on on the line graph.

**Comment by dmfRain4** [comment]
Another edit is that the shift that I observed must have been from how bar graphs are represented. If there are multiple rows on a bar graph, the different bars are off center so the bars will retain their x positions when brought across to other graph types.

In other news, I observed a strange scenario in which there was no data shown on the scatter plot when a particular row was made inactive. This needs much more testing. I feel as if all of the bugs are related to how we are representing/saving data in terms of graph types and active/innactive rows along with handling events for drawing the data on the graph.

**Comment by jmiller656** [comment]
Hide persistence has been completely fixed now.
