### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#60]
Anyone know why span is used and/or can we use a replacement that does the same? I think the html validation error might be fixed if another tag is used instead of span.

![screen shot 2015-06-19 at 13 41 25](https://cloud.githubusercontent.com/assets/11864006/8259275/486c0a1a-1689-11e5-929d-b4e426368c14.png)

**Comment by melissay94** [comment]
If this was a smaller, less complicated web application I would worry more about the errors we are getting , but since we're trying new things with the web app, I wouldn't be concerned as everything is working well together. Validation is really just standards you should be following, not rigid rules.
