### ISSUE TITLE
Add Reset Button For Graph Data Color

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#71]
As an enhancement, we can add a reset button for reseting the color of the graph, in the Graph Data section, to the default color. In other words, users changed the colors of the graph but decided they like the original better, they can use the reset button.

**Comment by smcintosh881** [comment]
Should we have a reset/refresh for the table as well? If you change a bunch of data but want the original back  or something. We could use a font-awesome icon for refresh and put that next to the other buttons below the table.

**Comment by smcintosh881** [comment]
![screen shot 2015-06-29 at 11 22 11 am](https://cloud.githubusercontent.com/assets/9065471/8411274/25535540-1e51-11e5-9ed0-bc589865864e.png)

something like this

**Comment by baozi90** [comment]
That looks good to me. :)

**Comment by smcintosh881** [comment]
should we make the reset button for the whole page? That way if the user make changes to the graph/table they don't like and want the original, instead of having to refresh the page and re-upload the file, should we make it so the re-fresh button does this?

**Comment by baozi90** [comment]
Separate issues are now created for reseting the background changes.

**Comment by baozi90** [comment]
We can add a reset button to the end of each of the checkboxes of the rows.

- a separate issue for table data reset will also be made

**Comment by melissay94** [comment]
We already have a ton of options for the user to change things in the UI. A reset for the table made sense since there are a finite amounts of undos you can perform, not to mention if you make 50 changes it would take forever to fix. Resets for the background and such made sense since the original is a pattern that you can't enter a value for. However, the lines are just solid colors and entering a new value would be pretty simple to get back to a color you would want.

**Comment by Rek3650** [comment]
:+1: I agree
