### ISSUE TITLE
Add Themes Feature For Background Color

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#88]
Add a feature that contains previously made color themes for the user to choose from. It will include color changed for the site, the graph, and the texts.

- So far, the visual for the theme is created.

**Comment by jmiller656** [comment]
I was checking out the themes and realized that basically all of them had the text being white and the background being black or vice versa. In this case, I'm not really sure it is necessary to have a feature for themes unless we have a use for all of the other colors in the themes, otherwise most will be identical.

**Comment by smcintosh881** [comment]
are those the ones melissa sent yesterday?

**Comment by baozi90** [comment]
Yup, that's the one she send.
