### ISSUE TITLE
Graph Data Print Page Doesn't Match

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#97]
The Graph Data section of the print page doesn't match up with the main page.

Missing:

- text input field (includes the color changed if any)
- checkbox (doesn't matter as much whether is there or not, but good to have: tells whether a line is unchecked or not)

This also makes the spacing look weird: not sure if the entire row for the color change should be taken out or try to put back the missing features.

**Comment by Rek3650** [comment]
I intentionally removed those things from the print page since there is no need for input fields on a piece of paper. You can still see the color changed by looking at the color of the text for the shape of a line. Your point about the checks is interesting. I don't think a check box is a good way to show this on a printed page. If the data is unimportant enough that they do not want to include it on the graph it might be best to exclude it from the graph data section altogether. We could also look into adding something else to that line that would indicate that it is excluded from the graph.
